### ISSUE TITLE
Debugger can't find source map for `react-devtools-core`

### ISSUE THREAD

**Issue by stefan-schweiger** [expo/vscode-expo#186]
### Description of the bug

When trying to start the debugger (e.g. with "Expo: Debug Expo app on a device or simulator, using Hermes" or through a config in launch.json) the following error appears in the Debug Console of VS Code.

`Could not read source map for file:///<path-to-my-app>/node_modules/react-devtools-core/dist/src/index.ts: ENOENT: no such file or directory, open '/<path-to-my-app>/node_modules/react-devtools-core/dist/src/index.js.map'`

### To Reproduce
What steps did you perform which led to this issue?

1. create new expo app with `npx create-expo-app my-app`
2. start expo with `npm run start`
3. open app in Expo Go (or custom dev client)
4. start debugger via "Expo: Debug Expo app on a device or simulator, using Hermes" command or launch.json

#### Expected behavior
The debugger to work

#### Actual behavior
Error that source map for `index.js` of module `react-devtools-core` could not be found (and there really neither exists a `index.js` or `index.js.map` file).

<img width="404" alt="image" src="https://github.com/expo/vscode-expo/assets/3532342/440c47ba-a496-4fbf-8636-99f4c6ddf354">

### Additional context

Extension Version: 1.0.1

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.15.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.15.1 - /usr/local/bin/npm
      Watchman: 2023.06.12.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.18 => 48.0.19 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
    npmGlobalPackages:
      eas-cli: 3.2.1
      expo-cli: 6.3.8
    Expo Workflow: managed
```

**Comment by byCedric** [comment]
Hi @stefan-schweiger! Thanks for the report. This is a known issue but should not affect any of the functionality within the Expo extension.

It's caused by this extension being published as minified code, with a sourcemap reference. But, it's not imported inside the app bundle, and therefore not picked up by the current sourcemap process.

I'll figure out if we can ignore this sourcemap from flagged like this. But for now, you can use everything as you would normally use it 😄
