### ISSUE TITLE
Check if we can only activate when workspace has `app.json` or `app.config.json`

### ISSUE THREAD

**Issue by byCedric** [expo/vscode-expo#2]
#### Old version
Right now it's activated on all events.

#### New version
It should only happen when Expo is found in the project.

### Additional context
It's not necessarily a waste, but good dev-hygiene :smile:

**Comment by JB1905** [comment]
I can take it 🙂

**Comment by byCedric** [comment]
Sorry for the delay again! If you want, go for it 😄 I'm not an expert with VSCode plugins. I know there are some interesting activation events that we can use, but looking forward to any contribution 👍

**Comment by ekfuhrmann** [comment]
Is there any progress on this feature? While working on multiple projects unrelated to Expo, it is a bit annoying always getting an error on VSCode bootup.

**Comment by byCedric** [comment]
@ekfuhrmann This has been sort-of implemented already.
  - We defer starting up to keep vscode as fast as possible ([source](https://github.com/expo/vscode-expo/blob/main/package.json#L36-L38) - [see why](https://github.com/microsoft/vscode/issues/110031))
  - The JSON Schema only activates for `app.json` ([source](https://github.com/expo/vscode-expo/blob/6304121f2d90161b15a26f2884c475b80dc0645e/src/manifest/config.ts#L26))
  - We fixed an issue where `app.json`'s `expo` was required and would warn if it's not defined (#63)

This is as specific as we can get it. If you know a better way, feel free to open a new issue.
