### ISSUE TITLE
Error after installation of extension in vsc

### ISSUE THREAD

**Issue by nicolasWD** [expo/vscode-expo#242]
### Description of the bug
On a fresh install from VSCode Extension manager and after restarting VS Code itself I get the following big error as a side notification down below:
![image](https://github.com/expo/vscode-expo/assets/106651239/cf5eb0f9-bd68-4629-ad2e-e1630d365ca4)

### To Reproduce

1. Installed extension
2. Restart VS Code and wait for it to appear on the bottom right

if I try to run the command 'Expo: Debug ... Hermes' then I get the following error:

![image](https://github.com/expo/vscode-expo/assets/106651239/dcf11e48-41d4-47ea-9c12-b6d377dccce8)

#### Expected behavior
I don't know, work? It's like when I was a kid and I was unwrapping presents and got disappointed when it was bed sheets.

#### Actual behavior
errors shown above

**Comment by byCedric** [comment]
Hi @nicolasWD! This issue is likely related to vscode being outdated. We don't use the telemetry API directly, instead, we rely on the `@vscode/telemetry-extension` (which [follows the user's telemetry preferences](https://code.visualstudio.com/docs/getstarted/telemetry) -- e.g. don't send anything when disabled).

What version of vscode are you using exactly?

**Comment by nicolasWD** [comment]
Hi @byCedric, thank you so much for the reply. The version details are below:

Version: 1.74.3 (user setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

I guess it is outdated based on the fact that it's a year old. I'll update and let you know

**Comment by nicolasWD** [comment]
Hi @byCedric, I just updated VSCode and everything works just fine. Thank you again for being quick to point out what was wrong.

**Comment by byCedric** [comment]
Glad we could resolve it fast :) Happy coding!
