### ISSUE TITLE
Certificate Not Valid Error on Expo Go for iOS and Android Platforms

### ISSUE THREAD

**Issue by Kreker990** [expo/vscode-expo#244]
Dear Expo Support Team,

I am encountering a certificate validation error when trying to launch my application on Expo Go across both iOS and Android platforms. The exact error message displayed is "certificate not valid," which prevents the app from starting through Expo Go.

Interestingly, when I remove the line "extra.eas.projectId" from my app.json file, the application starts and operates normally within Expo Go. This leads me to believe that the issue might be related to a recent attempt to update the certificate, as my other projects do not encounter this issue and function correctly.

The versions I am currently using are as follows:

Node.js: v21.5.0
npm/npx: 10.2.4
Expo SDK: ^49.0.0

Could you please provide guidance or a solution to resolve this certificate validation issue? Any assistance in troubleshooting this problem would be greatly appreciated, as it impacts the development and testing process of my application on the Expo platform.

Thank you for your support and looking forward to your prompt response.

Best regards, Bekzar

**Comment by byCedric** [comment]
Thanks for the issue report, this was an outage on our side: https://status.expo.dev/incidents/slnvd5h31nw5
