### ISSUE TITLE
Would preview modifiers work for `.js` or `.ts` extensions? 

### ISSUE THREAD

**Issue by harrisrobin** [expo/vscode-expo#62]
### Description of the feature
I love this feature, and would like to not lose it if I change my `app.json` -> `app.config.js`.

### Motivation
It's often necessary to use a `.js` extension, for example when using [environment variables ](https://docs.expo.dev/workflow/configuration/#app-config)

**Comment by matthops** [comment]
I'm also feeling the pain of not being able to use the preview modifier because I use app.config.js. Would be nice to have this functionality!
