### ISSUE TITLE
Expo extension for vscode: unable to perform

### ISSUE THREAD

**Issue by rounaksingh557** [expo/vscode-expo#81]
### Description of the bug
error thrown by the expo extension that cache cannot refresh.
![error](https://user-images.githubusercontent.com/75790404/142710689-ff1954ce-a5a6-4e39-853b-cb25789a54e7.png)

`Oops, looks like we couldn't activate the Expo manifest tools: Unable to perform cache refresh for C:\Users\rouna\AppData\Local\Expo\versions.json: Error: certificate has expired`

### To Reproduce

1. Open VS Code
2. Install Expo extension
3. Notice warning bottom right corner.

#### Expected behavior
Extension should have started working

#### Actual behavior
Throwing the error provided above.

### Additional context
Using Windows 11 and Nodejs 16.13.0

**Comment by rounaksingh557** [comment]
please solve this.

**Comment by rounaksingh557** [comment]
Fixed on my own.

**Comment by mukhlisakbr** [comment]
> Fixed on my own.

how do you fixed?

**Comment by rounaksingh557** [comment]
I deleted the file where expo extension stores it's config. Also I deleted the expo extension folder from vscode extension folder. 
After reintsalling the issue continued but later after reinstalling vscode, issue got fixed. I don't think that this is a permanent solution of this problem. I think there must be issues in the server of extension.

**Comment by rounaksingh557** [comment]
Do you have the exact same problem?

**Comment by Euclidean-Dev** [comment]
I have the exact same problem.

**Comment by donni106** [comment]
i ran into the same. after finding this issue without a real solution i will also try to delete some files and lets see what happens.

**Comment by MariyaC07** [comment]
Oops, looks like we couldn't activate the Expo manifest tools: Unable to perform cache refresh for C:\Users\mcher\AppData\Local\Expo\versions.json: Error: certificate has expired 

I have this issue
