### ISSUE TITLE
Hardcoded schema path

### ISSUE THREAD

**Issue by josmithua** [expo/vscode-expo#83]
#### Old version
Current settings have a hardcoded path to schema:
```json
  "json.schemas": [
    {
      "name": "vscode-expo-manifest",
      "url": "file:///Users/joshua/Library/Application%20Support/Code/User/globalStorage/bycedric.vscode-expo/manifest-44.0.0.json",
      "fileMatch": ["app.json", "app.config.json"]
    }
  ],
```

The above is from my Mac. When I open vscode on a Windows machine (settings sync turned on), there's sometimes conflicts or the setting gets overwritten.

The `url` should be a platform agnostic location, or an actual URL.

**Comment by byCedric** [comment]
Hi @josmithua! What would be a relative path that points to this pacakge's global storage? If we can find one that works, we can fix this 😄

**Comment by josmithua** [comment]
What if Expo hosted the manifest somewhere online, then you could just use a URL?
Something like `"url": "https://expo.dev/manifests/44.0.0.json"`

Although if vscode doesn't cache the contents it wouldn't work offline.

**Comment by EvanBacon** [comment]
Technically we do host the manifests publicly, just undocumented:
- https://api.expo.dev/v2/project/configuration/schema/45.0.0 → SDK 45

**Comment by byCedric** [comment]
We reimplemented the IntelliSense JSON Schema system, it will be released in the next version :) It might take some days/weeks, we are testing it internally first because it's a big change.
